### ISSUE TITLE
要求使用GitHub actions 下载

### ISSUE THREAD

**Issue by buiawpkgew1** [lx1169732264/pica_crawler#1]

**Comment by lx1169732264** [comment]
不错的建议, 用git actions提供的这台服务器不用代理也能访问哔咔, 项目的部署也变得非常方便

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/210131855-cc433431-362e-4e83-8556-e925f9f9c2a8.png)
这个是什么问题
