### ISSUE TITLE
开发者有考虑第一次收藏下载添加缓慢下载选项吗

### ISSUE THREAD

**Issue by Crosell127** [lx1169732264/pica_crawler#7]
比如说有很多人第一次使用这个工具，但是收藏夹里存在了很多漫画，导致第一次下载巨量漫画，可否考虑添加多个选项：缓慢下载（每下载完一个系列sleep一下）、立即全部下载等等

**Comment by lx1169732264** [comment]
加了`INTERVAL_TIME`这个环境变量, 每本漫画下载的间隔时间(秒), 不设置的话就是不间断地下载

**Comment by Crosell127** [comment]
再麻烦问一下，下载必须挂代理吗？ 我这边docker下载文件夹啥也没有？但是bika本身似乎支持线路选择，有些可以不挂代理

**Comment by lx1169732264** [comment]
> 再麻烦问一下，下载必须挂代理吗？ 我这边docker下载文件夹啥也没有？但是bika本身似乎支持线路选择，有些可以不挂代理

蛮早以前线路2是可以直连的. 但我这边现在不管是线路几, 都必须挂代理了, 这可能跟网络运营商有关. 代理相关的问题会报ConnectTimeoutError异常
而git actions这种运行方式用的是git的境外服务器, 也就不需要代理了

readme.md里有提到将`/app/comics`和`/app/output`两个目录挂载出来, 你看过这两个目录都是空的? 或者是运行过程中有报错日志?

我是一次性将收藏夹的所有内容用分页接口取出来的, 每页固定20条, 如果你收藏的数量特别大, 那要等一段时间才会进入下载阶段 :joy:

**Comment by Crosell127** [comment]
今天用在本地电脑上来了一下，看日志发现一直显示secret key error，但是格式参考问题汇总又没问题，很奇怪

lx ***@***.***>于2024年5月18日 周六13:19写道：
